export interface SurahMeta {
  number: number;
  name: string;
  nameArabic: string;
  meaning: string;
  verses: number;
  type: 'Meccan' | 'Medinan';
}

export const surahs: SurahMeta[] = [
  { number: 1, name: 'Al-Fatiha', nameArabic: 'الفاتحة', meaning: 'The Opening', verses: 7, type: 'Meccan' },
  { number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', meaning: 'The Cow', verses: 286, type: 'Medinan' },
  { number: 3, name: "Ali 'Imran", nameArabic: 'آل عمران', meaning: 'Family of Imran', verses: 200, type: 'Medinan' },
  { number: 4, name: 'An-Nisa', nameArabic: 'النساء', meaning: 'The Women', verses: 176, type: 'Medinan' },
  { number: 5, name: "Al-Ma'idah", nameArabic: 'المائدة', meaning: 'The Table Spread', verses: 120, type: 'Medinan' },
  { number: 6, name: "Al-An'am", nameArabic: 'الأنعام', meaning: 'The Cattle', verses: 165, type: 'Meccan' },
  { number: 7, name: "Al-A'raf", nameArabic: 'الأعراف', meaning: 'The Heights', verses: 206, type: 'Meccan' },
  { number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', meaning: 'The Spoils of War', verses: 75, type: 'Medinan' },
  { number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', meaning: 'The Repentance', verses: 129, type: 'Medinan' },
  { number: 10, name: 'Yunus', nameArabic: 'يونس', meaning: 'Jonah', verses: 109, type: 'Meccan' },
  { number: 11, name: 'Hud', nameArabic: 'هود', meaning: 'Hud', verses: 123, type: 'Meccan' },
  { number: 12, name: 'Yusuf', nameArabic: 'يوسف', meaning: 'Joseph', verses: 111, type: 'Meccan' },
  { number: 13, name: "Ar-Ra'd", nameArabic: 'الرعد', meaning: 'The Thunder', verses: 43, type: 'Medinan' },
  { number: 14, name: 'Ibrahim', nameArabic: 'إبراهيم', meaning: 'Abraham', verses: 52, type: 'Meccan' },
  { number: 15, name: 'Al-Hijr', nameArabic: 'الحجر', meaning: 'The Rocky Tract', verses: 99, type: 'Meccan' },
  { number: 16, name: 'An-Nahl', nameArabic: 'النحل', meaning: 'The Bee', verses: 128, type: 'Meccan' },
  { number: 17, name: "Al-Isra'", nameArabic: 'الإسراء', meaning: 'The Night Journey', verses: 111, type: 'Meccan' },
  { number: 18, name: 'Al-Kahf', nameArabic: 'الكهف', meaning: 'The Cave', verses: 110, type: 'Meccan' },
  { number: 19, name: 'Maryam', nameArabic: 'مريم', meaning: 'Mary', verses: 98, type: 'Meccan' },
  { number: 20, name: 'Ta-Ha', nameArabic: 'طه', meaning: 'Ta-Ha', verses: 135, type: 'Meccan' },
  { number: 21, name: "Al-Anbiya'", nameArabic: 'الأنبياء', meaning: 'The Prophets', verses: 112, type: 'Meccan' },
  { number: 22, name: 'Al-Hajj', nameArabic: 'الحج', meaning: 'The Pilgrimage', verses: 78, type: 'Medinan' },
  { number: 23, name: "Al-Mu'minun", nameArabic: 'المؤمنون', meaning: 'The Believers', verses: 118, type: 'Meccan' },
  { number: 24, name: 'An-Nur', nameArabic: 'النور', meaning: 'The Light', verses: 64, type: 'Medinan' },
  { number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان', meaning: 'The Criterion', verses: 77, type: 'Meccan' },
  { number: 26, name: "Ash-Shu'ara'", nameArabic: 'الشعراء', meaning: 'The Poets', verses: 227, type: 'Meccan' },
  { number: 27, name: 'An-Naml', nameArabic: 'النمل', meaning: 'The Ant', verses: 93, type: 'Meccan' },
  { number: 28, name: 'Al-Qasas', nameArabic: 'القصص', meaning: 'The Stories', verses: 88, type: 'Meccan' },
  { number: 29, name: "Al-'Ankabut", nameArabic: 'العنكبوت', meaning: 'The Spider', verses: 69, type: 'Meccan' },
  { number: 30, name: 'Ar-Rum', nameArabic: 'الروم', meaning: 'The Romans', verses: 60, type: 'Meccan' },
  { number: 31, name: 'Luqman', nameArabic: 'لقمان', meaning: 'Luqman', verses: 34, type: 'Meccan' },
  { number: 32, name: 'As-Sajdah', nameArabic: 'السجدة', meaning: 'The Prostration', verses: 30, type: 'Meccan' },
  { number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب', meaning: 'The Combined Forces', verses: 73, type: 'Medinan' },
  { number: 34, name: "Saba'", nameArabic: 'سبأ', meaning: 'Sheba', verses: 54, type: 'Meccan' },
  { number: 35, name: 'Fatir', nameArabic: 'فاطر', meaning: 'Originator', verses: 45, type: 'Meccan' },
  { number: 36, name: 'Ya-Sin', nameArabic: 'يس', meaning: 'Ya-Sin', verses: 83, type: 'Meccan' },
  { number: 37, name: 'As-Saffat', nameArabic: 'الصافات', meaning: 'Those in Ranks', verses: 182, type: 'Meccan' },
  { number: 38, name: 'Sad', nameArabic: 'ص', meaning: 'Sad', verses: 88, type: 'Meccan' },
  { number: 39, name: 'Az-Zumar', nameArabic: 'الزمر', meaning: 'The Troops', verses: 75, type: 'Meccan' },
  { number: 40, name: 'Ghafir', nameArabic: 'غافر', meaning: 'The Forgiver', verses: 85, type: 'Meccan' },
  { number: 41, name: 'Fussilat', nameArabic: 'فصلت', meaning: 'Explained in Detail', verses: 54, type: 'Meccan' },
  { number: 42, name: 'Ash-Shura', nameArabic: 'الشورى', meaning: 'The Consultation', verses: 53, type: 'Meccan' },
  { number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف', meaning: 'The Gold Adornments', verses: 89, type: 'Meccan' },
  { number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان', meaning: 'The Smoke', verses: 59, type: 'Meccan' },
  { number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية', meaning: 'The Crouching', verses: 37, type: 'Meccan' },
  { number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف', meaning: 'The Wind-Curved Sandhills', verses: 35, type: 'Meccan' },
  { number: 47, name: 'Muhammad', nameArabic: 'محمد', meaning: 'Muhammad', verses: 38, type: 'Medinan' },
  { number: 48, name: 'Al-Fath', nameArabic: 'الفتح', meaning: 'The Victory', verses: 29, type: 'Medinan' },
  { number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات', meaning: 'The Rooms', verses: 18, type: 'Medinan' },
  { number: 50, name: 'Qaf', nameArabic: 'ق', meaning: 'Qaf', verses: 45, type: 'Meccan' },
  { number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات', meaning: 'The Winnowing Winds', verses: 60, type: 'Meccan' },
  { number: 52, name: 'At-Tur', nameArabic: 'الطور', meaning: 'The Mount', verses: 49, type: 'Meccan' },
  { number: 53, name: 'An-Najm', nameArabic: 'النجم', meaning: 'The Star', verses: 62, type: 'Meccan' },
  { number: 54, name: 'Al-Qamar', nameArabic: 'القمر', meaning: 'The Moon', verses: 55, type: 'Meccan' },
  { number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن', meaning: 'The Beneficent', verses: 78, type: 'Medinan' },
  { number: 56, name: "Al-Waqi'ah", nameArabic: 'الواقعة', meaning: 'The Inevitable', verses: 96, type: 'Meccan' },
  { number: 57, name: 'Al-Hadid', nameArabic: 'الحديد', meaning: 'The Iron', verses: 29, type: 'Medinan' },
  { number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة', meaning: 'The Pleading Woman', verses: 22, type: 'Medinan' },
  { number: 59, name: 'Al-Hashr', nameArabic: 'الحشر', meaning: 'The Exile', verses: 24, type: 'Medinan' },
  { number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة', meaning: 'She That is Examined', verses: 13, type: 'Medinan' },
  { number: 61, name: 'As-Saf', nameArabic: 'الصف', meaning: 'The Ranks', verses: 14, type: 'Medinan' },
  { number: 62, name: "Al-Jumu'ah", nameArabic: 'الجمعة', meaning: 'The Congregation', verses: 11, type: 'Medinan' },
  { number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون', meaning: 'The Hypocrites', verses: 11, type: 'Medinan' },
  { number: 64, name: 'At-Taghabun', nameArabic: 'التغابن', meaning: 'The Mutual Disillusion', verses: 18, type: 'Medinan' },
  { number: 65, name: 'At-Talaq', nameArabic: 'الطلاق', meaning: 'The Divorce', verses: 12, type: 'Medinan' },
  { number: 66, name: 'At-Tahrim', nameArabic: 'التحريم', meaning: 'The Prohibition', verses: 12, type: 'Medinan' },
  { number: 67, name: 'Al-Mulk', nameArabic: 'الملك', meaning: 'The Sovereignty', verses: 30, type: 'Meccan' },
  { number: 68, name: 'Al-Qalam', nameArabic: 'القلم', meaning: 'The Pen', verses: 52, type: 'Meccan' },
  { number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة', meaning: 'The Reality', verses: 52, type: 'Meccan' },
  { number: 70, name: "Al-Ma'arij", nameArabic: 'المعارج', meaning: 'The Ascending Stairways', verses: 44, type: 'Meccan' },
  { number: 71, name: 'Nuh', nameArabic: 'نوح', meaning: 'Noah', verses: 28, type: 'Meccan' },
  { number: 72, name: 'Al-Jinn', nameArabic: 'الجن', meaning: 'The Jinn', verses: 28, type: 'Meccan' },
  { number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل', meaning: 'The Enshrouded One', verses: 20, type: 'Meccan' },
  { number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر', meaning: 'The Cloaked One', verses: 56, type: 'Meccan' },
  { number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة', meaning: 'The Resurrection', verses: 40, type: 'Meccan' },
  { number: 76, name: 'Al-Insan', nameArabic: 'الإنسان', meaning: 'The Human', verses: 31, type: 'Medinan' },
  { number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات', meaning: 'The Emissaries', verses: 50, type: 'Meccan' },
  { number: 78, name: "An-Naba'", nameArabic: 'النبأ', meaning: 'The Tidings', verses: 40, type: 'Meccan' },
  { number: 79, name: "An-Nazi'at", nameArabic: 'النازعات', meaning: 'Those Who Drag Forth', verses: 46, type: 'Meccan' },
  { number: 80, name: "'Abasa", nameArabic: 'عبس', meaning: 'He Frowned', verses: 42, type: 'Meccan' },
  { number: 81, name: 'At-Takwir', nameArabic: 'التكوير', meaning: 'The Overthrowing', verses: 29, type: 'Meccan' },
  { number: 82, name: 'Al-Infitar', nameArabic: 'الانفطار', meaning: 'The Cleaving', verses: 19, type: 'Meccan' },
  { number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين', meaning: 'The Defrauding', verses: 36, type: 'Meccan' },
  { number: 84, name: 'Al-Inshiqaq', nameArabic: 'الانشقاق', meaning: 'The Sundering', verses: 25, type: 'Meccan' },
  { number: 85, name: 'Al-Buruj', nameArabic: 'البروج', meaning: 'The Mansions of Stars', verses: 22, type: 'Meccan' },
  { number: 86, name: 'At-Tariq', nameArabic: 'الطارق', meaning: 'The Morning Star', verses: 17, type: 'Meccan' },
  { number: 87, name: "Al-A'la", nameArabic: 'الأعلى', meaning: 'The Most High', verses: 19, type: 'Meccan' },
  { number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية', meaning: 'The Overwhelming', verses: 26, type: 'Meccan' },
  { number: 89, name: 'Al-Fajr', nameArabic: 'الفجر', meaning: 'The Dawn', verses: 30, type: 'Meccan' },
  { number: 90, name: 'Al-Balad', nameArabic: 'البلد', meaning: 'The City', verses: 20, type: 'Meccan' },
  { number: 91, name: 'Ash-Shams', nameArabic: 'الشمس', meaning: 'The Sun', verses: 15, type: 'Meccan' },
  { number: 92, name: 'Al-Layl', nameArabic: 'الليل', meaning: 'The Night', verses: 21, type: 'Meccan' },
  { number: 93, name: 'Ad-Duhaa', nameArabic: 'الضحى', meaning: 'The Morning Hours', verses: 11, type: 'Meccan' },
  { number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح', meaning: 'The Relief', verses: 8, type: 'Meccan' },
  { number: 95, name: 'At-Tin', nameArabic: 'التين', meaning: 'The Fig', verses: 8, type: 'Meccan' },
  { number: 96, name: "Al-'Alaq", nameArabic: 'العلق', meaning: 'The Clot', verses: 19, type: 'Meccan' },
  { number: 97, name: 'Al-Qadr', nameArabic: 'القدر', meaning: 'The Power', verses: 5, type: 'Meccan' },
  { number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة', meaning: 'The Clear Proof', verses: 8, type: 'Medinan' },
  { number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة', meaning: 'The Earthquake', verses: 8, type: 'Medinan' },
  { number: 100, name: "Al-'Adiyat", nameArabic: 'العاديات', meaning: 'The Chargers', verses: 11, type: 'Meccan' },
  { number: 101, name: "Al-Qari'ah", nameArabic: 'القارعة', meaning: 'The Calamity', verses: 11, type: 'Meccan' },
  { number: 102, name: 'At-Takathur', nameArabic: 'التكاثر', meaning: 'The Rivalry in Worldly Increase', verses: 8, type: 'Meccan' },
  { number: 103, name: "Al-'Asr", nameArabic: 'العصر', meaning: 'The Declining Day', verses: 3, type: 'Meccan' },
  { number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة', meaning: 'The Traducer', verses: 9, type: 'Meccan' },
  { number: 105, name: 'Al-Fil', nameArabic: 'الفيل', meaning: 'The Elephant', verses: 5, type: 'Meccan' },
  { number: 106, name: 'Quraysh', nameArabic: 'قريش', meaning: 'Quraysh', verses: 4, type: 'Meccan' },
  { number: 107, name: "Al-Ma'un", nameArabic: 'الماعون', meaning: 'The Small Kindnesses', verses: 7, type: 'Meccan' },
  { number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر', meaning: 'The Abundance', verses: 3, type: 'Meccan' },
  { number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون', meaning: 'The Disbelievers', verses: 6, type: 'Meccan' },
  { number: 110, name: 'An-Nasr', nameArabic: 'النصر', meaning: 'The Divine Support', verses: 3, type: 'Medinan' },
  { number: 111, name: 'Al-Masad', nameArabic: 'المسد', meaning: 'The Palm Fiber', verses: 5, type: 'Meccan' },
  { number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص', meaning: 'The Sincerity', verses: 4, type: 'Meccan' },
  { number: 113, name: 'Al-Falaq', nameArabic: 'الفلق', meaning: 'The Daybreak', verses: 5, type: 'Meccan' },
  { number: 114, name: 'An-Nas', nameArabic: 'الناس', meaning: 'The Mankind', verses: 6, type: 'Meccan' },
];

export const PREVIEW_SURAHS = [1, 112, 113, 114];

export interface JuzMeta {
  juz: number;
  startSurah: number;
  startAyah: number;
}

export const juzData: JuzMeta[] = [
  { juz: 1, startSurah: 1, startAyah: 1 },
  { juz: 2, startSurah: 2, startAyah: 142 },
  { juz: 3, startSurah: 2, startAyah: 253 },
  { juz: 4, startSurah: 3, startAyah: 93 },
  { juz: 5, startSurah: 4, startAyah: 24 },
  { juz: 6, startSurah: 4, startAyah: 148 },
  { juz: 7, startSurah: 5, startAyah: 83 },
  { juz: 8, startSurah: 6, startAyah: 111 },
  { juz: 9, startSurah: 7, startAyah: 88 },
  { juz: 10, startSurah: 8, startAyah: 41 },
  { juz: 11, startSurah: 9, startAyah: 93 },
  { juz: 12, startSurah: 11, startAyah: 6 },
  { juz: 13, startSurah: 12, startAyah: 53 },
  { juz: 14, startSurah: 15, startAyah: 1 },
  { juz: 15, startSurah: 17, startAyah: 1 },
  { juz: 16, startSurah: 18, startAyah: 75 },
  { juz: 17, startSurah: 21, startAyah: 1 },
  { juz: 18, startSurah: 23, startAyah: 1 },
  { juz: 19, startSurah: 25, startAyah: 21 },
  { juz: 20, startSurah: 27, startAyah: 56 },
  { juz: 21, startSurah: 29, startAyah: 46 },
  { juz: 22, startSurah: 33, startAyah: 31 },
  { juz: 23, startSurah: 36, startAyah: 28 },
  { juz: 24, startSurah: 39, startAyah: 32 },
  { juz: 25, startSurah: 41, startAyah: 47 },
  { juz: 26, startSurah: 46, startAyah: 1 },
  { juz: 27, startSurah: 51, startAyah: 31 },
  { juz: 28, startSurah: 58, startAyah: 1 },
  { juz: 29, startSurah: 67, startAyah: 1 },
  { juz: 30, startSurah: 78, startAyah: 1 },
];

export const importantHijriDates = [
  { month: 1, day: 1, name: 'Islamic New Year', nameAr: 'رأس السنة الهجرية' },
  { month: 1, day: 10, name: 'Day of Ashura', nameAr: 'يوم عاشوراء' },
  { month: 3, day: 12, name: 'Mawlid al-Nabi', nameAr: 'المولد النبوي' },
  { month: 7, day: 27, name: "Isra' and Mi'raj", nameAr: 'الإسراء والمعراج' },
  { month: 8, day: 15, name: "Mid-Sha'ban", nameAr: 'ليلة النصف من شعبان' },
  { month: 9, day: 1, name: 'First day of Ramadan', nameAr: 'أول رمضان' },
  { month: 9, day: 27, name: 'Laylat al-Qadr (approx)', nameAr: 'ليلة القدر' },
  { month: 10, day: 1, name: 'Eid al-Fitr', nameAr: 'عيد الفطر' },
  { month: 12, day: 8, name: 'Day of Tarwiyah', nameAr: 'يوم التروية' },
  { month: 12, day: 9, name: 'Day of Arafah', nameAr: 'يوم عرفة' },
  { number: 12, day: 10, name: 'Eid al-Adha', nameAr: 'عيد الأضحى' },
];
